"""Generate the roadmap/index files. They are outputs, never inputs: the PreToolUse
hook blocks edits to them, and `orch render` rewrites them from state + plan."""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List

from . import ledger
from .common import Workflow, write_text_atomic
from .gates import Context, next_action
from . import plan as planmod

BANNER = "> Generated by `orch render` from workflow state — do not edit by hand."

STAGE_LABELS = {
    "readiness": "task start verification",
    "pm-start": "PM start check",
    "work": "work",
    "fix": "fix round",
    "pm-scope": "PM scope check",
    "verification": "completion verification",
    "review": "review",
    "pm-accept": "PM acceptance stamp",
    "pm-resolution": "PM review of resolution guidance",
}


def _h1(path: Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except OSError:
        pass
    return path.stem


def _md_link(text: str, rel: str) -> str:
    return f"[{text}]({rel})"


def render_all(wf: Workflow) -> None:
    ctx = Context(wf, fast=True)
    state = ctx.state
    try:
        nxt = next_action(ctx)
    except Exception as exc:  # rendering must never fail a command
        nxt = f"(could not compute: {exc}) — run `orch status`"
    _render_root(wf, ctx, nxt)
    _render_tasks(wf, ctx)
    _render_research(wf)
    _render_status(wf, ctx, nxt)
    for task_id in (state.get("tasks") or {}):
        _render_run_index(wf, ctx, task_id)


def _render_root(wf: Workflow, ctx: Context, nxt: str) -> None:
    state = ctx.state
    lines = [
        f"# {state.get('title', state.get('workflow_id'))}",
        "",
        BANNER,
        "",
        f"Workflow `{state.get('workflow_id')}` · phase **{state.get('phase')}** · "
        f"iteration {state.get('iteration', 1)} · plan revision {state.get('plan_revision', 1)}",
        "",
        f"**Next:** {nxt}",
        "",
        "## Document map",
        "",
        "| Document | What it is |",
        "| --- | --- |",
        f"| {_md_link('request.md', 'request.md')} | The original request, verbatim |",
        f"| {_md_link('plan.md', 'plan.md')} | The plan: requirements, approach, loop plan, quality gate, test strategy and test plan, final acceptance criteria, open questions |",
    ]
    if wf.architecture.exists():
        lines.append(f"| {_md_link('architecture.md', 'architecture.md')} | Architecture guidance every task must respect |")
    lines += [
        f"| {_md_link('gate.json', 'gate.json')} | Workspaces and quality-gate commands |",
        f"| {_md_link('decisions.md', 'decisions.md')} | Clarifications and human decisions made during the work (append-only) |",
        f"| {_md_link('tasks/index.md', 'tasks/index.md')} | Every task, grouped by orchestration loop, with status and links |",
        f"| {_md_link('research/index.md', 'research/index.md')} | Research that informed the plan |",
        "| `reviews/plan/` | Plan-stage reviews and PM audits |",
        "| `runs/T###/` | Per-task, per-attempt stage reports (see each `runs/T###/index.md`) |",
        "| `loops/L##/` | Loop entry/exit checks and loop-level gate runs |",
        "| `final/` | Whole-package review, verification, and acceptance |",
        f"| {_md_link('status.md', 'status.md')} | Detailed status |",
        "",
        "## Workspaces",
        "",
        "| Name | Path | Standard gate |",
        "| --- | --- | --- |",
    ]
    for name, entry in planmod.gate_workspaces(ctx.pkg.gate).items():
        if not isinstance(entry, dict):
            continue
        cmds = planmod.gate_commands(ctx.pkg.gate, name, "standard")
        lines.append(f"| {name} | `{entry.get('path')}` | {'; '.join(f'`{c}`' for c in cmds) or '—'} |")
    lines += ["", "## Orchestration loops", "", "| Loop | Status | Tasks |", "| --- | --- | --- |"]
    loops_state = state.get("loops") or {}
    for loop in ctx.pkg.loops():
        ids = ", ".join(t.id for t in ctx.pkg.tasks_in_loop(loop))
        lines.append(f"| {loop} | {(loops_state.get(str(loop)) or {}).get('status', 'PENDING')} | {ids} |")
    write_text_atomic(wf.root / "index.md", "\n".join(lines) + "\n")


def _render_tasks(wf: Workflow, ctx: Context) -> None:
    state = ctx.state
    tasks_state = state.get("tasks") or {}
    lines = ["# Tasks", "", BANNER, "", "Parent: [../index.md](../index.md)", ""]
    if not ctx.pkg.tasks:
        lines.append("No task documents yet.")
    for loop in ctx.pkg.loops():
        status = ((state.get("loops") or {}).get(str(loop)) or {}).get("status", "PENDING")
        lines += [
            f"## Loop {loop} — {status}",
            "",
            "| Task | Title | Type | Status | Attempt | Round | Depends on | Authors | Reviewers | Runs |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for spec in ctx.pkg.tasks_in_loop(loop):
            info = tasks_state.get(spec.id, {})
            run = f"[runs](../runs/{spec.id}/index.md)" if (wf.runs_dir / spec.id).is_dir() else "—"
            lines.append(
                f"| [{spec.id}]({spec.path.name}) | {spec.title} | {spec.type} | "
                f"{info.get('status', 'PLANNED')} | {info.get('attempt', 0)}/{info.get('attempt_budget', '-')} | "
                f"{info.get('round', 0)} | {', '.join(spec.depends_on) or '—'} | {', '.join(spec.authors)} | "
                f"{', '.join(spec.required_reviewers()) or '—'} | {run} |"
            )
        lines.append("")
    write_text_atomic(wf.tasks_dir / "index.md", "\n".join(lines) + "\n")


def _render_research(wf: Workflow) -> None:
    lines = ["# Research", "", BANNER, "", "Parent: [../index.md](../index.md)", ""]
    docs = sorted(p for p in wf.research_dir.glob("*.md") if p.name != "index.md") if wf.research_dir.is_dir() else []
    if not docs:
        lines.append("No research documents yet.")
    for path in docs:
        lines.append(f"- [{_h1(path)}]({path.name})")
    write_text_atomic(wf.research_dir / "index.md", "\n".join(lines) + "\n")


def _render_status(wf: Workflow, ctx: Context, nxt: str) -> None:
    state = ctx.state
    lines = [
        "# Workflow status",
        "",
        BANNER,
        "",
        f"- Workflow: `{state.get('workflow_id')}` — {state.get('title')}",
        f"- Phase: **{state.get('phase')}**",
        f"- Iteration: {state.get('iteration', 1)} · plan revision {state.get('plan_revision', 1)}",
        f"- Approved: {state.get('approved_at') or 'no'}",
        f"- Next: {nxt}",
    ]
    need = state.get("needs_human")
    if need:
        lines.append(f"- **Waiting for the human** ({need.get('kind')}): {need.get('summary')}")
    if state.get("block_reason"):
        lines.append(f"- Block reason: {state.get('block_reason')}")
    lines += ["", "## Tasks", ""]
    for tid, info in sorted((state.get("tasks") or {}).items()):
        spec = ctx.pkg.tasks.get(tid)
        title = spec.title if spec else "?"
        lines.append(
            f"- {tid} — {title} — {info.get('status')} — attempt {info.get('attempt', 0)}/"
            f"{info.get('attempt_budget', '-')} — round {info.get('round', 0)}/{info.get('review_budget', '-')}"
        )
    if not state.get("tasks"):
        lines.append("Tasks are initialized when the plan is approved.")
    questions = ctx.pkg.plan.questions
    lines += ["", "## Open questions (from plan.md)", ""]
    if not questions:
        lines.append("None recorded.")
    for q in questions:
        lines.append(f"- {q['id']}: {'RESOLVED' if q['resolved'] else 'UNRESOLVED'} — {q['text']}")
    lines += ["", "## Recent ledger events", ""]
    for entry in ctx.entries[-15:]:
        lines.append(f"- {_describe(entry)}")
    write_text_atomic(wf.root / "status.md", "\n".join(lines) + "\n")


def _describe(entry: Dict[str, Any]) -> str:
    kind = entry.get("kind")
    head = f"#{entry.get('seq')} {entry.get('ts', '')[:19]} {kind}"
    if kind == "agent_result":
        res = entry.get("result") or {}
        valid = "" if entry.get("valid") else " (INVALID: " + "; ".join(entry.get("errors") or []) + ")"
        return (f"{head} {entry.get('agent_type')} {res.get('stage')} {res.get('task') or ''} "
                f"verdict={res.get('verdict')} status={res.get('status')}{valid}")
    if kind in ("evidence", "gate"):
        return f"{head} {entry.get('phase') or entry.get('level')} {entry.get('task') or entry.get('scope')} passed={entry.get('passed')}"
    if kind == "transition":
        return f"{head} {entry.get('what')} {entry.get('task') or ''} -> {entry.get('to')}"
    if kind == "human":
        return f"{head} verb={entry.get('verb')}"
    return f"{head} {entry.get('task') or ''}"


RUN_FILE_RE = re.compile(r"^(\d+)-([a-z-]+?)(?:-r(\d+))?\.([a-z-]+)\.md$")


def _render_run_index(wf: Workflow, ctx: Context, task_id: str) -> None:
    root = wf.runs_dir / task_id
    if not root.is_dir():
        return
    lines = [f"# {task_id} — run history", "", BANNER, "", "Parent: [../../tasks/index.md](../../tasks/index.md)", ""]
    for attempt_dir in sorted(root.glob("a*")):
        if not attempt_dir.is_dir():
            continue
        lines += [f"## Attempt {attempt_dir.name[1:]}", ""]
        reports = sorted(attempt_dir.glob("*.md"))
        for path in reports:
            match = RUN_FILE_RE.match(path.name)
            if match:
                num, stage, rnd, agent = match.groups()
                label = STAGE_LABELS.get(stage, stage)
                rtext = f" (round {rnd})" if rnd is not None else ""
                lines.append(f"- {num}. {label}{rtext} — {agent} — [{path.name}]({attempt_dir.name}/{path.name})")
            else:
                lines.append(f"- [{path.name}]({attempt_dir.name}/{path.name})")
        extras = [p.name for p in attempt_dir.iterdir() if p.is_file() and p.suffix != ".md"]
        if extras:
            lines.append("")
            lines.append("CLI artifacts: " + ", ".join(f"`{n}`" for n in sorted(extras)))
        lines.append("")
    guidance = root / "resolution.orchestrator.md"
    if guidance.exists():
        lines.append(f"Resolution guidance: [resolution.orchestrator.md](resolution.orchestrator.md)")
    write_text_atomic(root / "index.md", "\n".join(lines) + "\n")


__all__ = ["render_all", "ledger"]
