version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: "/Users/jscott/.config/efm-langserver/log.log"
log-level: 5

tools:
  markdown-markdownlint: &markdown-markdownlint
    lint-command: "markdownlint -s"
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

# languages:
#   markdown:
#     - lint-command: "markdownlint -s"
#       lint-stdin: true
#       lint-after-open: true
#       lint-on-save: true
#       lint-formats:
#         - "%f:%l %m"
#         - "%f:%l:%c %m"
#         - "%f: %l: %m"
#
#   markdown-markdownlint:
#     - lint-command: "markdownlint -s"
#       lint-stdin: true
#       lint-after-open: true
#       lint-on-save: true
#       lint-formats:
#         - "%f:%l %m"
#         - "%f:%l:%c %m"
#         - "%f: %l: %m"

languages:
  markdown:
    - <<: *markdown-markdownlint
